- fix in checking is netforking is up.
Changed files:
    portmap.init -> 1.5

diff --git a/portmap.init b/portmap.init
--- a/portmap.init
+++ b/portmap.init
@@ -21,7 +21,10 @@
 [ -f /etc/sysconfig/portmap ] && . /etc/sysconfig/portmap
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Portmap service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
